name: BunnyNationsCore
version: '${version}'
main: dev.thebjoredcraft.bunnynationscore.BunnyNationsCore
api-version: '1.20'
author: TheBjoRedCraft
commands:
  money:
    permission: bunnynationscore.command.money
  pay:
    permission: bunnynationscore.command.pay
  broadcastas:
    permission: bunnynationscore.command.broadcastas
    aliases:
      - bcas
  broadcast:
    aliases:
      - bc
    permission: bunnynationscore.command.broadcast
  rules:
